import Head from "next/head"
import { useEffect, useRef, useState } from "react"

import maplibregl from "maplibre-gl";
import * as pmtiles from "pmtiles";
import layer from "./positron_style.json"


// const [initialLon, initialLat] = [41.1533, 20.1683]
const [initialLon, initialLat] = [-76.5059133431, 37.6227077717]

const Map = () => {
  const mapContainer = useRef(null);
  const map = useRef(null);
  const [lng] = useState(initialLon);
  const [lat] = useState(initialLat);

  const [zoom] = useState(6);

  useEffect(() => {
    if (map.current) return;

    let protocol = new pmtiles.Protocol();
    maplibregl.addProtocol("pmtiles", protocol.tile);

    map.current = new maplibregl.Map({
      container: mapContainer.current as any,
      style: {
        glyphs: "/virginia-hospital-distance/glyphs/{fontstack}/{range}.pbf",
        version: 8,
        "sources": {
          "openmaptiles": {
            "type": "vector",
            "url": "pmtiles:///virginia-hospital-distance/virginia-smaller.pmtiles"
          },
          "isochrone_0": {
            "type": "geojson",
            "data": "/virginia-hospital-distance/polygon_0.json",
          },
          "isochrone_1": {
            "type": "geojson",
            "data": "/virginia-hospital-distance/polygon_1.json"
          },
          "isochrone_2": {
            "type": "geojson",
            "data": "/virginia-hospital-distance/polygon_2.json"
          },
          "isochrone_3": {
            "type": "geojson",
            "data": "/virginia-hospital-distance/polygon_3.json"
          }
        },
        layers: layer as any
      },
      // style: "https://demotiles.maplibre.org/style.json",
      center: [lng, lat],
      zoom: zoom,
      minZoom: 7,
      maxBounds: [
        [-84.71490710282056,
          35.77320086387027],
        [-73.94080914265395,
          39.73148308878754]],
      customAttribution: "© OpenMapTiles © OpenStreetMap contributors"
    }) as any;
  });

  return (
    <div className="map-wrap">
      <div ref={mapContainer} className="map" />
      <div id="state-legend" className="legend">
        <h4>Driving Distance
          to Nearest Hospital</h4>
        <div className="legend-element"><span style={{ backgroundColor: "#fde725" }}></span>&lt; 10 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#35b779" }}></span>&lt; 20 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#31688e" }}></span>&lt; 30 minutes</div>
        <div className="legend-element"><span style={{ backgroundColor: "#440154" }}></span>&lt; 40 minutes</div>
      </div>
    </div>
  );
}


export default function Isochrone() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Map></Map>
      </main>
    </>
  )
}
